### PR TITLE
idr redirect (add-on)

### PR DESCRIPTION
**Pull request by joshmoore**
Since you are remove playbooks that I would need to update, I've done this work on top of your branch, @manics.

### CODE REVIEW

**Comment by manics** [comment]
Unfortunately it's not that easy... the following are still under `roles/` and shouldn't be prefixed:
```python
!ls roles > here.txt
!git diff ..pr5 -- . ':!requirements.yml' grep -E '^\+'|grep role: | awk '{print $4}' | sort -u > add.txt

with open('here.txt') as f: here=set(f.read().split())
with open('add.txt') as f: add=set(f.read().split())
add.intersection({'openmicroscopy.%s'%d for d in here})

{'openmicroscopy.active-directory-samba-share',
 'openmicroscopy.ansible',
 'openmicroscopy.debug-dumpallvars',
 'openmicroscopy.dell-update',
 'openmicroscopy.devspace',
 'openmicroscopy.docker-dns-client',
 'openmicroscopy.docker-dns-server',
 'openmicroscopy.gpfs',
 'openmicroscopy.jenkinsslave',
 'openmicroscopy.network',
 'openmicroscopy.nfs-ganesha-share',
 'openmicroscopy.omero-build',
 'openmicroscopy.omero-build-cpp',
 'openmicroscopy.omero-runtime',
 'openmicroscopy.omero-scripts-dependencies',
 'openmicroscopy.omero-web-apps-build-dependencies',
 'openmicroscopy.openldap-devel',
 'openmicroscopy.openstack-prepare',
 'openmicroscopy.python-devel',
 'openmicroscopy.server-swap',
 'openmicroscopy.sphinx-build',
 'openmicroscopy.system-monitor-agent',
 'openmicroscopy.yum-excludes'}
```

**Comment by joshmoore** [comment]
Then closing this. Leaving you to run that script and add it to your existing PR.

**Comment by manics** [comment]
That script only finds the errors... the quickest option is to duplicate the requirements file and later migrate the playbooks individually so that they're tested- this also means we don't have to worry about role versions. I can do that if you're happy.

**Comment by joshmoore** [comment]
GFI

**Pull request closed without merging**
